---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(stargazer)
library(estimatr)
library(AER)
library(ggplot2)
library(cowplot)
library(sandwich)
library(lmtest)
library(dplyr)
library(lfe) #felm is the function from this package 
library(here)
```

```{r}
#setwd(dirname(rstudioapi::getActiveDocumentContext()$path)) #Set's directory where script is located
getwd()

# IMPORT CSV DATA
FULTON <- read.csv(here("data", "FULTON.csv")) %>%
  mutate(log_tots = log(tots), #log of total sales 
         log_price = log(pricelevel))


# SUMMARY STATISTICS
stargazer(FULTON, type="text", digits=2)
```

```{r}
# BASIC OLS REGRESSION of log total sales on log price
ols <- lm(formula = log_tots ~ log_price, data=FULTON)
summary(ols)
```
Interp: If the price goesup by 1%, the tots would go down by 0.56. 

** First Statge regression**

What's the effect of an extra increase in m/s speed in wind of price??

```{r}
# FIRST_STAGE REGRESSION - JUST-IDENTIFIED MODEL
fs1 <- lm(formula = log_price ~ windspd, data=FULTON)
summary(fs1)
```

Interp: I 1 m/s increase in wind speed increases the total sales by 0.72 (unit). 

**Two-Stage Least Squares Regression:**

```{r}
# TSLS - JUST-IDENTIFIED MODEL
tsls1 <- ivreg(log_tots ~ log_price | windspd, data = FULTON)
summary(tsls1)
```

```{r}
# Calculate robust standard errors for OLS and FS1 using starprep()
se_ols_fs1 <- starprep(ols,fs1, stat = c("std.error"), se_type = "HC2", alpha = 0.05) 

# Calculate robust standard errors sandwich and lmtest packages (starprep() does not like ivreg() objects)
se_tsls11 <- coeftest(tsls1, vcov = vcovHC(tsls1, type = "HC2"))[, "Std. Error"]

# Combine standard errors and output results with stargazer()
se_models <- append(se_ols_fs1,list(se_tsls11))
stargazer(ols, fs1, tsls1, se = se_models, type="text")
```

```{r}
# Other approach using the lfe package #####################

# Estimate the first two models
ols_felm <- felm(formula = log_tots ~ log_price, data=FULTON)
fs1_felm <- felm(formula = log_price ~ windspd, data=FULTON)

# Estimate 2SLS
# "log_tots ~ 1" is not the first stage, it is the all variables in the first stage, BUT the endogenous one
# | 0 | means that we are not including fixed effects here.

tsls1_felm <- felm(formula = log_tots ~ 1 | 0 | (log_price ~ windspd),  data=FULTON)

# The robust standard errors are calculated (not reported) by default in felm(), so here we can fetch and combine them
# It might be HC1, but the documentation is not great. 

se_models_felm <- list(ols_felm$rse,fs1_felm$rse, tsls1_felm$rse)

stargazer(ols_felm, fs1_felm, tsls1_felm, se = se_models_felm, type="text")

```

