---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(stargazer)
library(estimatr)
library(ggplot2)
library(plm)
library(sandwich)
library(lmtest)

# SET WORKING DIRECTORY
setwd(dirname(rstudioapi::getActiveDocumentContext()$path)) #Automatically sets directory where script is saved
getwd()
```

```{r}
# IMPORT CSV DATA and CREATE SUBSET for 1988
SWTF <- read.csv("SW_TrafficFatality.csv")
SWTF88 <- subset(SWTF, year == "1988")
SWTF82 <- subset(SWTF, year == "1982")

# SUMMARY STATISTICS
stargazer(SWTF, type="text", digits=2)
```

```{r}
# BASIC OLS REGRESSION
m88 <- lm(formula = frate ~ beertax, data=SWTF88)

se_m88 <- starprep(m88, stat = c("std.error"), se_type = "HC2", alpha = 0.05) 
stargazer(m88, se = se_m88, type="text")
```

```{r}
# SCATTERPLOT with REGRESSION LINE
ggplot(data=SWTF88, aes(x=beertax, y=frate)) +
  geom_smooth(method=lm) +
  geom_text(aes(label=state), size = 3) 
```

```{r}
# FIRST DIFFERENCE MODEL FOR 1988 AND 1982
dfrate <- SWTF88$frate - SWTF82$frate
dbtax <- SWTF88$beertax - SWTF82$beertax
fd8882 <- lm(formula = dfrate ~ dbtax)

se_fd8882 <- starprep(fd8882, stat = c("std.error"), se_type = "HC2", alpha = 0.05) 
stargazer(fd8882, se = se_fd8882, type="text")
```

```{r}
# ESTIMATE THE BASIC WITHIN FIXED EFFECTS REGRESSION
within1 <- plm(frate ~ beertax + state, data = SWTF,
           index = c("state", "year"), 
           model = "within")

# Calculate standard errors (note slightly different procedure with plm package)
se_within1 <- coeftest(within1, vcov = vcovHC(within1, type = "HC2"))[, "Std. Error"]
# Reformat standard errors for stargazer()
se_within1 <- list(se_within1)

# Output results with stargazer
stargazer(within1, se = se_within1, type="text")
```

```{r}
# LEAST SQUARES DUMMY VARIABLES REGRESSION
lsdv <- lm(formula = frate ~ beertax + as.factor(state), data=SWTF)

se_lsdv <- starprep(lsdv, stat = c("std.error"), se_type = "HC2", alpha = 0.05) 
stargazer(lsdv, keep=c("beertax"), se = se_fd8882, type="text")
```

